### ISSUE TITLE
In the cart: The customer expected to select date + time after selecting "urb-it specific time"

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#11]
The option to select date + time is missing in the cart after selecting urb-it specific time.

Ivar made this change in september and reason was UX related and somebody decided to let the user select this in the cart.

Have spoken to more customer and they think this is worse customer experience.
Please enable same ability to select date + time in cart as it is in the checkout.
- And copy they selected entries while going in to the checkout

**Comment by TommyUrbit** [comment]
Why did we remove the option to select the date + hour + minute in the cart for specific time. It is only at the checkout. Before we could select in cart as well and that was copied in to the checkout setting ?

**Comment by slobodan** [comment]
@TommyUrbit not sure if I'm the right person to respond to the why it was removed question.
