### ISSUE TITLE
In the cart - the price is not adding the VAT - customer needed to change 103,20 SEK to 129 SEK to show it as 129 SEK

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#12]
This is the third time I have seen this problem. All settings I know of seems OK related to how the price+tax is handled. The tax is configured to be included and enabled but the 103,20 SEK is still 103,20 SEK in cart items and should be 129 SEK with VAT including. Need help tracking this issue down. Have a personal test site with the same issue. Customer is now changing 103,20 to get it to show 129 SEK.

**Comment by slobodan** [comment]
@TommyUrbit can I get access to a site with this issue? Is this shipping price or product price?

**Comment by TommyUrbit** [comment]
Sent you an email and access credentials to a site with that issue

**Comment by TommyUrbit** [comment]
Hi, on one of the site this was fixed by doing:
Go to - WooCommerce - Setting - Tax - Standard rates - Add - SE and 25 % and save

That part seemed like changed from 2.5-2.6 similar to shippin zones + classes.
Now it works OK - closing issue
