### ISSUE TITLE
Klarna: In the Checkout - expected 2 columns checkout was a one column checkout

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#13]
After adding the code snippet for the 2 column the checkout works for showing urb-it options and dialogue but it is still a 1 column page in the checkout. Is this OK , the earlier customers and documentations shows in: https://github.com/urbitassociates/Integration/blob/master/KCO%20Integration%20Guide_v1.pdf
Needs to here that this is OK and how it should and why this is different between customer.

**Comment by slobodan** [comment]
@TommyUrbit can you share the snippet you used? If you do something like this, it should be fine:

```
[woocommerce_klarna_checkout col="right"]
[woocommerce_klarna_checkout_widget col="left" order_note="hide"]
```

**Comment by TommyUrbit** [comment]
Hi,


this is the snippet we used:



[woocommerce_klarna_checkout_widget col="left"][woocommerce_klarna_checkout col="right"]


Tommy Hägvall | Integration Manager

M Work:    +46730845767
M Private: +46733188766

@: tommy@urbit.com<mailto:tommy@urb-it.com> new

@: tommy@urb-it.com<mailto:tommy@urb-it.com> old
W: www.urb-it.com<http://www.urb-it.com/>
SkypeID: tommyhagvallurbit
Kontor: Malmskillnadsgatan 32, 111 51 Stockholm (Epicenter, våning 8)




 [https://ci5.googleusercontent.com/proxy/wfZfx3eLb44QnI9GHSVsTtQH6K_QsaXxs6y4ga6YlrQ9-EUy0G9Do6n3hrddU9oNChPnXDJSx95j4-k4qg=s0-d-e1-ft#http://urb-it.com/img/logo_signatur.png]



________________________________
Från: Slobodan Manic <notifications@github.com>
Skickat: den 9 januari 2017 12:01
Till: urbitassociates/woocommerce-urb-it-shipping
Kopia: Tommy Hägvall; Mention
Ämne: Re: [urbitassociates/woocommerce-urb-it-shipping] Klarna: In the Checkout - expected 2 columns checkout was a one column checkout (#13)


@TommyUrbit<https://github.com/TommyUrbit> can you share the snippet you used? If you do something like this, it should be fine:

[woocommerce_klarna_checkout col="right"]
[woocommerce_klarna_checkout_widget col="left" order_note="hide"]


-

**Comment by slobodan** [comment]
@TommyUrbit what's the URL? If public.

**Comment by slobodan** [comment]
Is this at styleport.se?

**Comment by TommyUrbit** [comment]
Yes it is styleport.se

**Comment by slobodan** [comment]
Thanks. Still waiting to get access to that site, but from looking at their checkout page, it seems like they are not using our cart widget there. The HTML is different.

**Comment by TommyUrbit** [comment]
So it is by design right ? Do you have a proposal for how could we improve that UX experience ?

**Comment by slobodan** [comment]
Yes, that is how our plugin works.

The best way to hide elements is by using CSS selectors, please let me know if that will work for them.
