### ISSUE TITLE
In the Checkout - selecting "urb-it specific time" enables the Days + Time input dialog for urb-it

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#14]
This dialog is correctly showing "Dag" in Swedish for the section label but the dropdown has incorrectly "Day" in English as a first entry and should be "Idag" instead.

"Day" needs to be changed to "Idag" for Swedish.
ex. "Idag, Tisdag, Onsdag, Torsdag"

"Day" in dropdown needs to be changed to "Today" for English
"Day" in dropdown needs to be changed to "Aujourd'hui" for French

**SE** Sample
urbit.cart.totals.shipping.type.urbit.specific.day.label = Dag
# urbit.cart.totals.shipping.type.urbit.specific.day.dropdown = "Idag, Tisdag, Onsdag, Torsdag"

urbit.checkout.totals.shipping.type.urbit.specific.day.label = Dag
# urbit.checkout.totals.shipping.type.urbit.specific.day.dropdown = "Idag, Tisdag, Onsdag, Torsdag"

**EN** Sample
urbit.cart.totals.shipping.type.urbit.specific.day.label = Day
# urbit.cart.totals.shipping.type.urbit.specific.day.dropdown = "Today, Tuesday, Wednesday, Thursday"

 urbit.checkout.totals.shipping.type.urbit.specific.day.label = Day
# urbit.checkout.totals.shipping.type.urbit.specific.day.dropdown = "Today, Tuesday, Wednesday, Thursday"

**FR** Sample
urbit.cart.totals.shipping.type.urbit.specific.day.label = Jour
# urbit.cart.totals.shipping.type.urbit.specific.day.dropdown = "Aujourd'hui, Mardi, Mercredi, Jeudi"

urbit.checkout.totals.shipping.type.urbit.specific.day.label = Jour
# urbit.checkout.totals.shipping.type.urbit.specific.day.dropdown = "Aujourd'hui, Mardi, Mercredi, Jeudi"

**Comment by slobodan** [comment]
+replace time input field with two selects for hours and minutes (discussed in Skype call)
