### ISSUE TITLE
Klarna: The process only works if you enter the Postal Code validation on the product detail page + select urb-it as a delivery option first at the Cart level

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#15]
In order to have urb-it + Klarna work together is today 

To have the user to:
- enter postal code validation on product page
- select urb-it as a delivery  method in the cart
- and then do the rest in the Checkout for Klarna

Some issues and questions - need for a better solution:
- If customers not enters the postal code validation - the necessary fields for Klarna Checkout + urb-it is not working correctly
- some customers wants to go directly to the checkout without passing the postal code validation and passing via the cart

Can we improve this or inform the user clearer and have a more solid and robust behaviour ?

**Comment by slobodan** [comment]
@TommyUrbit this is not how it works for me. The site has Storefront theme, latest versions of all plugins.

I add the product to cart from homepage, then proceed to Klarna Checkout page, where I can enter my postal code and after that address, in addition to being able to select Urb-it shipping methods.

Where does what you described occur (which site)?

**Comment by TommyUrbit** [comment]
styleport.se

**Comment by slobodan** [comment]
Same issue as #13 - they are using something else for cart widget. Will check what once I get login details.
