### ISSUE TITLE
Klarna: If you do not change to "urbit specific time" in the cart -> you can not change it in the checkout

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#16]
There should be able to change the delivery method in the Checkout
today you need to "back" to the cart and to change it there to another delivery method and forward again to checkout
In the checkout - if urb-it specifc time is selected - it is not even possible to change to free delivery 

Need to be able to change the delivery method again in the checkout

**Comment by slobodan** [comment]
@TommyUrbit same question as #15 which site is this happening on?

**Comment by TommyUrbit** [comment]
You should have got admin access to the site a couple of days ago
