### ISSUE TITLE
In the summary for shipping alternatives - the amount fields and value for ex. 29 SEK is showed twice

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#17]
After the urb-it shipping plugin is installed the total + summary total pricing for the delivery methods is showing the amount in two places for the built in "Delivery cost". The urb-it cost is showed once. Since the customer only had one shipping alternativ they wonder why this happens.

See attached screenshot:
![image001_lyko](https://cloud.githubusercontent.com/assets/19204873/21603048/925bc4bc-d19a-11e6-92f8-7a88e1b3cef5.png)

Need to understand why this is happening and how to only show it once per delivery method

**Comment by slobodan** [comment]
@TommyUrbit I believe this is cart widget in Klarna Checkout page. 

If that is the case, the number of the rate is row summary and shows price of selected shipping option. It allows row totals in the table to be right aligned for easier overview.

Please confirm this is where the screenshot came from.

**Comment by slobodan** [comment]
@TommyUrbit this is Styleport, too? They currently don't use our cart widget, and the widget works as I described in previous message. 

Can we close this one?

**Comment by TommyUrbit** [comment]
The dilemma is that that entire option was not shown before urb-it delivery option was added as a second entry. It is the add of urb-it as a delivery option that showed that existing other delivery option to be shown with two sums ... the customer do not like that and wants o know why.

**Comment by slobodan** [comment]
Here's what the shipping row of KCO cart widget looks like with one shipping option, and multiple shipping options.

<img width="459" alt="screen shot 2017-01-16 at 10 33 25" src="https://cloud.githubusercontent.com/assets/129607/21977677/71706a9a-dbd7-11e6-94ff-9afb13a747f6.png">

<img width="450" alt="screen shot 2017-01-16 at 10 34 31" src="https://cloud.githubusercontent.com/assets/129607/21977683/76e3a438-dbd7-11e6-82e6-029080de47ea.png">

It's not an Urb-it thing, this is how our plugin works. If there's only one option given, then the price is only shown on the right, if there are multiple options, their cost needs to be visible at all times, so customer can know how much an option will cost, before changing to it. 

If a particular merchant would like to see this changed, the row summary price on the right can be hidden using CSS, something like:

`#kco-page-shipping-total * { display: none; }`

should do the trick. But again, if this is Styleport, they are using something else and that screenshot from issue details is not what their checkout page looks like now.

**Comment by TommyUrbit** [comment]
OK sounds good - closing issue - we will inform Styleport that it is unique for them and with the CSS "fix" - Closing
