### ISSUE TITLE
Great Britain is not part of the code

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#2]
Hi, I just saw that Great Britain , London is missing in the following snippet.
- not sure how they are used , I assume we need to add more country codes

protected $country_codes = array(
            '46', // Sweden
            '33'  // France
        );
        protected $mobile_prefixes = array(
            '07', // Generic
            '06'  // France
        );

**Comment by slobodan** [comment]
@TommyUrbit can you send me list of all country codes and mobile prefixes that need to be added here?

**Comment by TommyUrbit** [comment]
I am working on an internal decision regarding this - need also to get an answer from the developer that made this change.
That change was implemented in some specific Paris and London based "Omnistores". They where manually added to each site and very custom. "Omsnistore" = WooCommerce with a specific Template and Customer UX, themes code very specific for landing page customers. I will check and get back

**Comment by TommyUrbit** [comment]
OK - Now this is known - we will do it manually and different in a case by case basis - until we complete the policy and list for different more countries to come in future expansion. Some reluctancy to implement a change as of now. We will wait until it is needed and better tested
