### ISSUE TITLE
The Postal Code JQuery script is loaded to early and decrease the performance of the page

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#4]
On the Product Detail page where Postal Code validation check is visibile.
The script for loading the JQuery related to the element is loaded already in the beginning. It is really sensitiv to network performance and affects latency and slower performance.

Please move script to the end and make sure the element is not blocking the load of the page and also make the page load time quicker.

**Comment by slobodan** [comment]
@TommyUrbit was this one fixed since the issue was created? The code is currently loaded in the footer, after the entire page has loaded.

https://github.com/urbitassociates/woocommerce-urb-it-shipping/blob/master/includes/class-frontend-postcode-validator.php#L63

**Comment by TommyUrbit** [comment]
Ahh , it is fixed then. Closing the issue.
