### ISSUE TITLE
The amount up/down entry field for quantity is to narrow

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#6]
On the product detail page

Dependent on screen size, template and if responsive the numbers is not visible and the width is to narrow for the numbers to show .

This is to narrow
.woocommerce .quantity .qty {
    width: 3.631em;
    text-align: center;
}

This is OK
.woocommerce .quantity .qty {
    **width: 70px;**
    text-align: center;
}

**Comment by slobodan** [comment]
@TommyUrbit this is not an Urb-it specific issue, is it?

**Comment by TommyUrbit** [comment]
No it is not urb-it specific. It really depends on the themes selected. In many themes the selection is to narrow. Is it possible for us to increase that width with an override ? This is both in the product detail and in the cart.

**Comment by TommyUrbit** [comment]
I will close this request - it is not related to Shipping module - more indirectly impacted dependant on theme

**Comment by TommyUrbit** [comment]
Closing - just for information
