### ISSUE TITLE
If allow backorder and stock level is  0 - urb-it shipping option should be disabled

### ISSUE THREAD

**Issue by TommyUrbit** [urbitassociates/woocommerce-urb-it-shipping#7]
If allow backorder and stock level is  0 - urb-it shipping option should be disabled

Stock management is enabled on product level and variation/article level
Stock level is managed on product level and on variation/article level
Allow backorders ? Is set on product level and on variation/article level

If item has Stock level = 0 and Allow backorders = Do not allow then the "add to cart" is disabled.

If item has Stock level = 0 and Allow backorders = Allow or Allow, but notify the customer then it is possible to add item to cart and the urb-it shipping option should not be possible to select and should 
be disabled.

Today orders are created with urb-it delivery but the item is not in store and is not shipped until 2 days later to store. Same problem in the marketplace app.

Please disable the combination - urb-it should only be visibile if the item has stock level more than 0 and more than the quantity amount in the order/cart.

**Comment by slobodan** [comment]
@TommyUrbit does the update I sent as PR fix this issue?

**Comment by TommyUrbit** [comment]
Yes it works perfect ! Thanx.
